function hi() {
    alert("Bo'oh'o'wa'er")
}
function vote() {
    alert("Whyyyyyy? Bananas, as shown in the images, (carousel) are very nutritional and provide great health benifits. Bananas make you happier, the give your muscles strength, and are good for cramps. Ok, I'm done now. That's enough for one paragraph. Though with my fullest extent of my fantastic volcabulary, I provide extra, crucial words to this paragraph using the art of wasting words. Ok, I'm actually done now.")
    setTimeout(3000)
    alert (
        "Dear Team, I believe an opportunity exists to differentiate the Leg product by highlighting its connection to traditional farming methods.These techniques often emphasize reducing food waste, a value that was also prevalent in the 1980s.Investigating how relevant this selling point is to our current customer base could provide valuable insights to consider. Best regards, Whoever is reading this"
    )
    alert ("Since we now proceed to spout unconsiderably formal bits of nonsense, I believe that pneumonoultramicroscopicsilicovolcanoconiosis is a lung disease caused by prolonged inhalation of silica gas. The short name for this preposterously long word of pneumonoultramicroscopicsilicovolcanoconiosis is silicosis. We do not prefer to use the longer variation in a simplified conversation, especially when speaking unformally or in a very dire situation where a man or woman has actually been bestowed upon with this monstrosity of a word, though pronouncing this may have a larger struggle than the lung issues produced by this, even harder when you're struggling to breathe and your doctor says you have pneumonoultrascopicsilicovolcanoconiosis. You may struggle to pronounciate this word in your sick form, because your lungs would have trouble speaking in the situation. You may also feel like a sick joke, and  yes, that's pneumonoultramicroscopicsilicovolcanoconiosis for you. Your doctor may spare you the thought of the uncomfortable senstation the word grants you, but learning this word is not only completely useless, it also wastes your time, just like this paragraph.")
}